version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=572053745994.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-ecr-repo
      - docker --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodejs-repo-ecr:latest .
      - echo Build successful 
      - docker tag nodejs-repo-ecr:latest 572053745994.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-ecr-repo
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker images
      - docker push 572053745994.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-ecr-repo
      - printf '[{"name":"nodejs-container","imageUri":"%s"}]' 572053745994.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-ecr-repo > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
